export const GET_DOCUMENT_LIST_REQUEST = 'documentReducer/GET_DOCUMENT_LIST_REQUEST';
export const GET_DOCUMENT_LIST_SUCCESS = 'documentReducer/GET_DOCUMENT_LIST_SUCCESS';
export const GET_DOCUMENT_LIST_FAILED = 'documentReducer/GET_DOCUMENT_LIST_FAILED';
export const DELETE_DOCUMENT_REQUEST = 'documentReducer/DELETE_DOCUMENT_REQUEST';
export const DELETE_DOCUMENT_SUCCESS = 'documentReducer/DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAILED = 'documentReducer/DELETE_DOCUMENT_FAILED';